INSERT INTO "Breed" (name, description, characteristics, colors, patterns, temperament, size, lifespan, image_url, created_at, updated_at)
VALUES 
    ('Persian', 'Known for their long, luxurious coat and sweet personality, Persian cats are gentle and calm companions.', 'Long-haired, flat face, stocky build', 'White, Black, Blue, Red, Cream, Silver, Golden', 'Solid, Tabby, Bicolor, Himalayan', 'Gentle, Calm, Affectionate', 'Medium to Large', '12-17 years', 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=300&fit=crop', NOW(), NOW()),
    ('Maine Coon', 'Large, friendly cats with tufted ears and bushy tails. Known as gentle giants of the cat world.', 'Large size, tufted ears, long tail, water-resistant coat', 'Brown, Black, Red, Blue, Cream, White', 'Tabby, Solid, Tortoiseshell, Calico', 'Friendly, Intelligent, Playful', 'Large', '13-14 years', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=300&fit=crop', NOW(), NOW()),
    ('British Shorthair', 'Sturdy, round cats with dense coats and calm temperaments. Perfect family companions.', 'Round face, dense coat, sturdy build', 'Blue, Black, White, Red, Cream, Silver', 'Solid, Tabby, Bicolor', 'Calm, Independent, Loyal', 'Medium to Large', '14-20 years', 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=300&fit=crop', NOW(), NOW()),
    ('Ragdoll', 'Large, docile cats that go limp when picked up. Known for their striking blue eyes and semi-long coat.', 'Large size, blue eyes, semi-long coat, docile nature', 'Seal, Blue, Chocolate, Lilac, Red, Cream', 'Colorpoint, Mitted, Bicolor', 'Docile, Calm, Affectionate', 'Large', '13-18 years', 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=300&fit=crop', NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

INSERT INTO "Kitten" (name, breed_id, gender, age_weeks, color, price, description, health_records, images, status, featured, created_at, updated_at)
VALUES 
    ('Luna', (SELECT id FROM "Breed" WHERE name = 'Persian' LIMIT 1), 'Female', 12, 'Silver Persian', 1200.00, 'Beautiful silver Persian kitten with stunning green eyes. Very affectionate and loves to be held.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Sophie', (SELECT id FROM "Breed" WHERE name = 'Persian' LIMIT 1), 'Female', 10, 'White Persian', 1300.00, 'Pristine white Persian kitten with blue eyes. Extremely gentle and loves attention.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Princess', (SELECT id FROM "Breed" WHERE name = 'Persian' LIMIT 1), 'Female', 14, 'Golden Persian', 1400.00, 'Stunning golden Persian with luxurious coat. Very regal and elegant personality.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Shadow', (SELECT id FROM "Breed" WHERE name = 'Persian' LIMIT 1), 'Male', 16, 'Black Persian', 1100.00, 'Mysterious black Persian with copper eyes. Very calm and observant nature.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'reserved', false, NOW(), NOW()),
    ('Cream', (SELECT id FROM "Breed" WHERE name = 'Persian' LIMIT 1), 'Female', 11, 'Cream Persian', 1250.00, 'Delicate cream Persian with pink nose. Very sweet and loving temperament.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Max', (SELECT id FROM "Breed" WHERE name = 'Maine Coon' LIMIT 1), 'Male', 16, 'Brown Tabby', 800.00, 'Playful Maine Coon kitten with classic brown tabby markings. Great with children and other pets.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Leo', (SELECT id FROM "Breed" WHERE name = 'Maine Coon' LIMIT 1), 'Male', 20, 'Black Maine Coon', 900.00, 'Majestic black Maine Coon with tufted ears. Very intelligent and playful.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Tiger', (SELECT id FROM "Breed" WHERE name = 'Maine Coon' LIMIT 1), 'Male', 18, 'Orange Tabby', 850.00, 'Striking orange tabby Maine Coon with white markings. Very energetic and friendly.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Storm', (SELECT id FROM "Breed" WHERE name = 'Maine Coon' LIMIT 1), 'Male', 15, 'Gray Maine Coon', 950.00, 'Beautiful gray Maine Coon with silver highlights. Very gentle and loving.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Fluffy', (SELECT id FROM "Breed" WHERE name = 'Maine Coon' LIMIT 1), 'Female', 13, 'White Maine Coon', 1000.00, 'Gorgeous white Maine Coon with blue eyes. Very affectionate and loyal.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Bella', (SELECT id FROM "Breed" WHERE name = 'British Shorthair' LIMIT 1), 'Female', 14, 'Blue British Shorthair', 1000.00, 'Gorgeous blue British Shorthair with perfect round features. Calm and gentle personality.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Winston', (SELECT id FROM "Breed" WHERE name = 'British Shorthair' LIMIT 1), 'Male', 17, 'Gray British Shorthair', 1100.00, 'Handsome gray British Shorthair with golden eyes. Very dignified and calm.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Pearl', (SELECT id FROM "Breed" WHERE name = 'British Shorthair' LIMIT 1), 'Female', 12, 'White British Shorthair', 1200.00, 'Elegant white British Shorthair with copper eyes. Very sweet and gentle.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Coal', (SELECT id FROM "Breed" WHERE name = 'British Shorthair' LIMIT 1), 'Male', 19, 'Black British Shorthair', 1050.00, 'Stunning black British Shorthair with copper eyes. Very loyal and affectionate.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Cinnamon', (SELECT id FROM "Breed" WHERE name = 'British Shorthair' LIMIT 1), 'Female', 11, 'Cream British Shorthair', 1150.00, 'Beautiful cream British Shorthair with green eyes. Very playful and loving.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Oliver', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Male', 18, 'Seal Point Ragdoll', 1100.00, 'Stunning seal point Ragdoll with bright blue eyes. Very docile and loving nature.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop'], 'reserved', true, NOW(), NOW()),
    ('Angel', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Female', 13, 'Blue Point Ragdoll', 1200.00, 'Beautiful blue point Ragdoll with striking blue eyes. Very gentle and affectionate.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Mittens', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Male', 15, 'Mitted Ragdoll', 1250.00, 'Adorable mitted Ragdoll with white paws and blue eyes. Very sweet and calm.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Lily', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Female', 16, 'Lilac Point Ragdoll', 1300.00, 'Exquisite lilac point Ragdoll with lavender markings. Very elegant and loving.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Chocolate', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Male', 14, 'Chocolate Point Ragdoll', 1150.00, 'Handsome chocolate point Ragdoll with warm brown markings. Very affectionate and loyal.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Snow', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Female', 12, 'White Ragdoll', 1400.00, 'Pristine white Ragdoll with blue eyes. Very gentle and perfect for families.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()),
    ('Smokey', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Male', 17, 'Gray Point Ragdoll', 1200.00, 'Beautiful gray point Ragdoll with silver markings. Very calm and loving companion.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop'], 'available', false, NOW(), NOW()),
    ('Ruby', (SELECT id FROM "Breed" WHERE name = 'Ragdoll' LIMIT 1), 'Female', 15, 'Red Point Ragdoll', 1350.00, 'Stunning red point Ragdoll with warm orange markings. Very playful and affectionate.', 'Vaccinated, Dewormed, Health Certificate', ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop'], 'available', true, NOW(), NOW()); 